### ISSUE TITLE
Zeta function crashes

### ISSUE THREAD

**Issue by urbach** [ZhanlinWang/zetaFuncCal#9]
Hi Zhanlin,

your zeta function implementation crashes for the following input parameters. Do you know/could you check where this comes from? Thanks, Carsten

Tolerance               1.e-6
l                       2
m                       0
dVec            0       0       2       
gamma           1.621159
Lamda           1
qSqur           0.2788716
verbose         1

**Comment by ZhanlinWang** [comment]
Hi Carsten,
   I have tested these parameters and I think the problem comes from dVec.When I range other parameters, the program will give reasonable result. Only if dVec=(0, 0, 2), the program crashes.
I think the reason is that there is one term in \vec{r} composed of  ( \vec{n} - \vec{d}/2),  which will 
give 0 if  \vec{d} = (0, 0, 2) and \vec{n} = (0, 0, 1).I think this is the source of this bug.
Zhanlin

**Comment by urbach** [comment]
you need to replace

        rVecMod = sqrt( (pow(nDotd,2.0)/dModSqur + dModSqur/4.0 - nDotd)/pow(gamma,2.0)
                        + nSqur  - pow(nDotd,2.0)/dModSqur);
	if(rVecMod < DBL_EPSILON) {
	  cosPolarAngle = 1.;
	  azAngle = 0.;
	}
	else {
	  cosPolarAngle = ((nDotd*dVec[2]/dModSqur-dVec[2]/2.0)/gamma + (n3-nDotd*dVec[2]/dModSqur))
	    / rVecMod;
	  azAngle=azimutalAngle((nDotd*dVec[0]/dModSqur-dVec[0]/2.0)/gamma+(n1-nDotd*dVec[0]/dModSqur),
				(nDotd*dVec[1]/dModSqur-dVec[1]/2.0)/gamma + (n2-nDotd*dVec[1]/dModSqur));
	}
